export interface ProductType {
  id: number;
  title: string;
  thumbnail: string;
  description: string;
  price: number;
  tag: null | string;
  discount: null | number;
  categories: string[];
  backgroundColor?: string;
  filter?: string;
}

export interface Products {
  hotDealProducts: ProductType[];
  newStockProducts: ProductType[];
  bestProductsData: ProductType[];
  headphonesData: ProductType[];
}

export const products: Products = {
  hotDealProducts: [
    {
      id: 1,
      title: "B&W McLaren",
      thumbnail: "/images/hot-deal/product-1.png",
      description: "Special-edition over-ear noise cancelling headphones",
      price: 50,
      tag: null,
      discount: null,
      categories: [""],
      backgroundColor: "#FFF9F5",
    },
    {
      id: 2,
      title: "Lavic 3 PRO",
      thumbnail: "/images/hot-deal/product-2.png",
      description: "Fly Longer, Sense More Industry-Leading Performance",
      price: 50,
      tag: null,
      discount: null,
      categories: [""],
      backgroundColor: "#F4FCFC",
    },
    {
      id: 3,
      title: "Smart Watch",
      thumbnail: "/images/hot-deal/product-3.png",
      description: "Experience the biggest screen ever on the Smart Watch",
      price: 50,
      tag: null,
      discount: null,
      categories: [""],
      backgroundColor: "#F6F9FF",
    },
  ],
  newStockProducts: [
    {
      id: 1,
      title: "Go360 4Pro",
      thumbnail: "/images/new-stock/product-1.png",
      description:
        "Celebrating the long-standing, award-winning partnership between Bowers & Wilkins and McLaren Automotive and the McLaren supercars and hypercars in which Bowers & Wilkins has been integrated.",
      price: 449,
      tag: "Featured",
      discount: null,
      categories: ["Electronics", "Camera"],
      backgroundColor: "#F4EEE9",
    },
    {
      id: 2,
      title: "Sony WH-1000XM6",
      thumbnail: "/images/products/sony-wh-1000xm6-main.webp",
      description:
        "Trådlösa premiumhörlurar med avancerad brusreducering, klart ljud och upp till 30 timmars batteritid.",
      price: 3990,
      tag: null,
      discount: null,
      categories: ["Hörlurar"],
      backgroundColor: "#F3F5F8",
    },
    {
      id: 3,
      title: "Insta360 ACE Pro",
      thumbnail: "/images/new-stock/product-3.png",
      description:
        "Celebrating the long-standing, award-winning partnership between Bowers & Wilkins and McLaren Automotive and the McLaren supercars and hypercars in which Bowers & Wilkins has been integrated.",
      price: 399,
      tag: null,
      discount: 30,
      categories: ["Electronics", "Camera"],
      backgroundColor: "#FFF6F6",
    },
    {
      id: 4,
      title: "Xbox Wireless Controller",
      thumbnail: "/images/new-stock/product-4.png",
      description:
        "Celebrating the long-standing, award-winning partnership between Bowers & Wilkins and McLaren Automotive and the McLaren supercars and hypercars in which Bowers & Wilkins has been integrated.",
      price: 849,
      tag: null,
      discount: null,
      categories: ["Electronics", "Gaming"],
      backgroundColor: "#F6F3FD",
    },
  ],
  bestProductsData: [
    {
      id: 1,
      title: "Go360 4Pro",
      thumbnail: "/images/bestProducts/camera-1.png",
      description: "360-degree action camera with dual screens",
      price: 449,
      tag: "Featured",
      discount: null,
      categories: ["cameras"],
      filter: "cameras",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 2,
      title: "Go360 Compact 3",
      thumbnail: "/images/bestProducts/camera-2.png",
      description: "Compact 360-degree camera with flip screen",
      price: 199,
      tag: null,
      discount: null,
      categories: ["cameras"],
      filter: "cameras",
      backgroundColor: "#EEF7F8",
    },
    {
      id: 3,
      title: "Insta360 ACE Pro",
      thumbnail: "/images/bestProducts/camera-3.png",
      description: "Advanced action camera with flip screen",
      price: 299,
      tag: null,
      discount: 30,
      categories: ["cameras", "accessories"],
      filter: "cameras",
      backgroundColor: "#FFF6F6",
    },
    {
      id: 4,
      title: "Xbox Wireless Controller",
      thumbnail: "/images/bestProducts/camera-4.png",
      description: "Wireless controller for gaming",
      price: 849,
      tag: null,
      discount: null,
      categories: ["accessories"],
      filter: "cameras",
      backgroundColor: "#EDF4FA",
    },
    {
      id: 5,
      title: "GoPro Hero 12 Black",
      thumbnail: "/images/bestProducts/camera-5.png",
      description: "Latest GoPro action camera with advanced features",
      price: 299.99,
      tag: "New",
      discount: null,
      categories: ["cameras", "virtualReality"],
      filter: "cameras",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 6,
      title: "GoPro MAX",
      thumbnail: "/images/bestProducts/camera-6.png",
      description: "360-degree action camera with dual lens",
      price: 399.99,
      tag: null,
      discount: null,
      categories: ["cameras", "accessories"],
      filter: "cameras",
      backgroundColor: "#F2EEF8",
    },
    {
      id: 7,
      title: "Insta360 ACE Pro",
      thumbnail: "/images/bestProducts/camera-7.png",
      description: "Compact action camera with mounting dock",
      price: 299,
      tag: null,
      discount: null,
      categories: ["cameras", "virtualReality"],
      filter: "cameras",
      backgroundColor: "#EDF8F0",
    },
    {
      id: 8,
      title: "Xbox Wireless Controller",
      thumbnail: "/images/bestProducts/camera-8.png",
      description: "360-degree camera controller",
      price: 849,
      tag: null,
      discount: null,
      categories: ["accessories"],
      filter: "cameras",
      backgroundColor: "#F8ECEC",
    },
    {
      id: 9,
      title: "B&W Pi7 S2",
      thumbnail: "/images/headphones/product-1.png",
      description: "Premium wireless earbuds with adaptive noise cancellation",
      price: 319,
      tag: "New",
      discount: null,
      categories: ["headphones", "accessories"],
      filter: "headphones",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 11,
      title: "B&W Px7 S2e",
      thumbnail: "/images/headphones/product-3.png",
      description: "Noise-cancelling over-ear headphones",
      price: 319,
      tag: null,
      discount: null,
      categories: ["headphones"],
      filter: "headphones",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 12,
      title: "SoundPods",
      thumbnail: "/images/headphones/product-4.png",
      description: "Premium wireless over-ear headphones",
      price: 459,
      tag: "New",
      discount: null,
      categories: ["headphones", "virtualReality"],
      filter: "headphones",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 13,
      title: "WH-1000XM4",
      thumbnail: "/images/headphones/product-5.png",
      description: "Industry-leading noise cancelling headphones",
      price: 249,
      tag: null,
      discount: null,
      categories: ["headphones"],
      filter: "headphones",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 14,
      title: "LinkBuds S Earbuds",
      thumbnail: "/images/headphones/product-6.png",
      description: "Compact wireless earbuds with smart features",
      price: 149,
      tag: null,
      discount: null,
      categories: ["headphones", "earbuds"],
      filter: "headphones",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 15,
      title: "Apple Watch Series 8",
      thumbnail: "/images/bestProducts/smart-watch-1.png",
      description: "Compact wireless earbuds with smart features",
      price: 149,
      tag: null,
      discount: null,
      categories: ["smartWatch"],
      filter: "smartWatch",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 16,
      title: "Samsung Galaxy Watch 5",
      thumbnail: "/images/bestProducts/smart-watch-2.png",
      description: "Compact wireless earbuds with smart features",
      price: 200,
      tag: null,
      discount: null,
      categories: ["smartWatch", "virtualReality"],
      filter: "smartWatch",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 17,
      title: "Pixel Watch",
      thumbnail: "/images/bestProducts/smart-watch-3.png",
      description: "Compact wireless earbuds with smart features",
      price: 150,
      tag: null,
      discount: null,
      categories: ["smartWatch"],
      filter: "smartWatch",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 18,
      title: "Xiaomi Watch",
      thumbnail: "/images/bestProducts/smart-watch-4.png",
      description: "Compact wireless earbuds with smart features",
      price: 150,
      tag: null,
      discount: null,
      categories: ["smartWatch"],
      filter: "smartWatch",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 19,
      title: "Apple Watch Series 9",
      thumbnail: "/images/bestProducts/smart-watch-5.png",
      description: "Compact wireless earbuds with smart features",
      price: 180,
      tag: null,
      discount: null,
      categories: ["smartWatch"],
      filter: "smartWatch",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 20,
      title: "Apple Watch Series 5",
      thumbnail: "/images/bestProducts/smart-watch-6.png",
      description: "Compact wireless earbuds with smart features",
      price: 120,
      tag: null,
      discount: null,
      categories: ["smartWatch"],
      filter: "smartWatch",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 20.1,
      title: "Samsung Watch",
      thumbnail: "/images/bestProducts/smart-watch-7.png",
      description: "Compact wireless earbuds with smart features",
      price: 90,
      tag: null,
      discount: null,
      categories: ["smartWatch"],
      filter: "smartWatch",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 21,
      title: "Dji Drone",
      thumbnail: "/images/bestProducts/drone-1.png",
      description: "Compact wireless earbuds with smart features",
      price: 90,
      tag: null,
      discount: null,
      categories: ["drone", "accessories"],
      filter: "drone",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 22,
      title: "Dji 505 Drone",
      thumbnail: "/images/bestProducts/drone-2.png",
      description: "Compact wireless earbuds with smart features",
      price: 120,
      tag: null,
      discount: null,
      categories: ["drone", "accessories"],
      filter: "drone",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 23,
      title: "Dji Small Drone",
      thumbnail: "/images/bestProducts/drone-3.png",
      description: "Compact wireless earbuds with smart features",
      price: 170,
      tag: null,
      discount: null,
      categories: ["drone"],
      filter: "drone",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 24,
      title: "Sony Night Vision Drone",
      thumbnail: "/images/bestProducts/drone-4.png",
      description: "Compact wireless earbuds with smart features",
      price: 230,
      tag: null,
      discount: null,
      categories: ["drone"],
      filter: "drone",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 25,
      title: "Sony White Drone",
      thumbnail: "/images/bestProducts/drone-5.png",
      description: "Compact wireless earbuds with smart features",
      price: 250,
      tag: null,
      discount: null,
      categories: ["drone", "virtualReality"],
      filter: "drone",
      backgroundColor: "#ECF2F9",
    },
    {
      id: 26,
      title: "Xiaomi Drone",
      thumbnail: "/images/bestProducts/drone-6.png",
      description: "Compact wireless earbuds with smart features",
      price: 150,
      tag: null,
      discount: null,
      categories: ["drone"],
      filter: "drone",
      backgroundColor: "#ECF2F9",
    },
  ],
  headphonesData: [
    {
      id: 1,
      title: "B&W Pi7 S2",
      thumbnail: "/images/headphones/product-1.png",
      description: "Premium wireless earbuds with adaptive noise cancellation",
      price: 319,
      tag: "New",
      discount: null,
      categories: ["headphones", "earbuds"],
      filter: "headphones",
      backgroundColor: "#ffffff",
    },
    {
      id: 2,
      title: "aBEAT",
      thumbnail: "/images/headphones/product-2.png",
      description: "Over-ear wireless headphones with premium sound",
      price: 149.9,
      tag: null,
      discount: null,
      categories: ["headphones"],
      filter: "headphones",
      backgroundColor: "#ffffff",
    },
    {
      id: 3,
      title: "B&W Px7 S2e",
      thumbnail: "/images/headphones/product-3.png",
      description: "Noise-cancelling over-ear headphones",
      price: 319,
      tag: null,
      discount: null,
      categories: ["headphones"],
      filter: "headphones",
      backgroundColor: "#ffffff",
    },
    {
      id: 4,
      title: "SoundPods",
      thumbnail: "/images/headphones/product-4.png",
      description: "Premium wireless over-ear headphones",
      price: 459,
      tag: "New",
      discount: null,
      categories: ["headphones"],
      filter: "headphones",
      backgroundColor: "#ffffff",
    },
    {
      id: 5,
      title: "WH-1000XM4",
      thumbnail: "/images/headphones/product-5.png",
      description: "Industry-leading noise cancelling headphones",
      price: 249,
      tag: null,
      discount: null,
      categories: ["headphones"],
      filter: "headphones",
      backgroundColor: "#ffffff",
    },
    {
      id: 6,
      title: "LinkBuds S Earbuds",
      thumbnail: "/images/headphones/product-6.png",
      description: "Compact wireless earbuds with smart features",
      price: 149,
      tag: null,
      discount: null,
      categories: ["headphones", "earbuds"],
      filter: "headphones",
      backgroundColor: "#ffffff",
    },
  ],
};
